import type { Metadata } from "next";
import { Inter, Monofett } from "next/font/google";

import { Grainy } from "@/components/grainy";
import { cn } from "@/utils/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen font-mono bg-white")}>
        <Grainy />
        {children}
      </body>
    </html>
  );
}
